### ISSUE TITLE
Fails to backup comic as a cbz file

### ISSUE THREAD

**Issue by HeartofSteel** [Cortys/comic-backup#63] opened 2017-03-22 21:52 UTC
Hello,

I had this issue about a year ago and am having it again with backing up any comics from comixology. I backed up dozens last year, but ever since the new update, I haven't been able to backup any properly. Instead of saving in the usual cbz format, they save as file codes titled "a51ee388-7632-4d3b-8384-b7d653d3aec4" and other names like that one.

At first, I assumed it was the comic length, but even normal comics that 23-27 pages produce the same results. I have the most updated version of both Chrome and Comixology Backup. I'm using Windows 10. Saving in CBZ format. Jpg page format. Minimum page swap interval is 600 ms. Page skip delay is 1200 ms.

Please help. I have no idea what could be causing this. I've tried reinstalling several times to no avail.

Thank you for the assistance.

**Comment by Cortys** [comment] 2017-03-26 17:50
Hi!

I just tried reproducing your issue without success using Windows 10 (version 1607, build 14393.969), Mac OS 10.12.3 and Linux 4.10 with the latest Chrome stable release (57.0.2987.110 64bit) and a fresh install of version 2.3.3 of the extension (which uses cbz+jpg by default).

I tried various types of comics: Standard single page comics, singe page mangas, dual-page-only mangas and guided-view-narrative comics.

Do you notice anything that could be different with your setup?

Also can you please give me a screenshot of the options page of the extension, just to make sure there is no obvious difference.

Thanks!

**Comment by HeartofSteel** [comment] 2017-03-26 18:00
Hi!

Thank you for the response.

I'm using Windows 7 (which as always worked in the past) on standard PC (the same one I have always had and been using).

Below are the two screen shots of my extension options page. Thank you again for the assistance.

![capture](https://cloud.githubusercontent.com/assets/19141288/24333793/99dcaaee-122c-11e7-81cd-52557affce81.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19141288/24333795/9e6c1856-122c-11e7-977d-9a3acaa3bcbe.PNG)

**Comment by Cortys** [comment] 2017-03-26 18:55
Works fine for me on Windows 7 with the same settings.

Could you try using a different device and see if you can reproduce the issue there?

**Comment by cecoates** [comment] 2017-06-25 05:53
I have a similar issue.

Debian Stable (Stretch). Using the Version 61.0.3135.4 (Official Build) dev (64-bit) build of Chrome.

Comics end up in zip files like "tmp1498368168007.zip" 

Interestingly, if I'm saving to CBZ and it comes out like the above, the files inside the zip are logically named like page00, page01, etc.

However, if I choose the single page mode, ALL saved pages come out with names like the above, which makes zipping them into any kind of order difficult for large books, since they're not named in a logical order.

Same result on small, medium, and large graphic novels, and single issues.

I'm sticking with JPG and CBZ because renaming a zip file isn't a big deal, and I'm still just grateful to have a way to backup my purchases (which was awesome recently when we had a power outage and I could still read books on my laptop and tablet without needing to download).

**Comment by cecoates** [comment] 2017-06-26 19:25
At first I thought it was because I chose the wrong setting, but I was able to reproduce the OPs issue on my system.

Debian Stretch, Chrome Version 61.0.3135.4 (Official Build) dev (64-bit), and fresh install of the extension downloaded from GH.

Options:

![selection_011](https://user-images.githubusercontent.com/10121835/27556316-b2ff44dc-5a7a-11e7-95ee-c7a6739c622a.png)

How the file looks downloaded:

![selection_010](https://user-images.githubusercontent.com/10121835/27556328-c1a0a08a-5a7a-11e7-9b49-3b2ff6c23b99.png)

On Linux, however, it's still detected as a .zip file and you can just rename it to .cbz.

I'm not sure if it's related, but when I choose the "single images" option, the files come out with every image randomly named like the above .zip:

![selection_002](https://user-images.githubusercontent.com/10121835/27556399-0167ebce-5a7b-11e7-9a59-380d4fcc2888.png)

Which makes it hard to figure out what order the pages go in. With the .zip or .cbz option, the files within are named in a logical page000, page001, etc. fashion.

Instead for bigger comics I've been having more luck increasing the page skip delay drastically, to 15000ms.

Thanks for all the hard work!

**Comment by Cortys** [comment] 2018-08-29 11:59
Duplicate of #52.

**Closed by Cortys** 2018-08-29 11:59 UTC
