### ISSUE TITLE
Download never start/no download after scanning

### ISSUE THREAD

**Issue by puppyg93** [Cortys/comic-backup#75] opened 2018-04-18 17:40 UTC
I follow all the steps and instruction in downloading the file. After successfully completing the final 2 steps which is click thumbnail 1 and 2, I did click and it says scan complete but no download prompt or download happens. No error or warning as well, just nothing happen. Any help on this?

**Comment by sgbeal** [comment] 2018-04-18 18:07
On my system it mis-names the downloads - they are named with what appears to be a random UUID. Sort your Downloads directory by time and make sure it didn't download it using the wrong name. (It does not prompt for downloads, it just places them in the default download directory.)

**Comment by MrNakaan** [comment] 2018-04-18 18:09
@sgbeal I get that issue when I don't download into an archive. Download into an archive and they pages will be numbered from 000 - xxx.

**Comment by sgbeal** [comment] 2018-04-18 19:14
My pages are numbered right, just not the final archive. i have to rename (UUID) to blah.cbz. It's not broken, really, just weird.

**Comment by puppyg93** [comment] 2018-04-18 21:01
@MrNakaan it works now when download into archive. Pages also numbered 000.xxx.

**Comment by Cortys** [comment] 2018-08-29 12:01
Duplicate of #52.

**Closed** 2018-08-29 12:01 UTC
