### ISSUE TITLE
CBZ files will not open

### ISSUE THREAD

**Issue by AndrewD2** [Cortys/comic-backup#59] opened 2017-01-23 22:29 UTC
If I download the files as individual images and then zip them myself everything works fine. If I use the cbz or zip settings (compressed or uncompressed) I receive this kind of error in my reader.

![image](https://cloud.githubusercontent.com/assets/8145893/22225200/8a6371e2-e18f-11e6-9126-b76c01c3e57c.png)

This error only appears with cbz/zip files created from this extension. On my computer I use 7zip and have no issues.

I am not sure what is causing this issue, my Chrome console gives this error numerous times whenever I try to make one:
```
Uncaught TypeError: onend is not a function
    at zip.js:772
    at BlobWriter.writeUint8Array (zip.js:283)
    at writeFooter (zip.js:770)
    at onflush (zip.js:309)
    at zip.js:341
    at BlobWriter.writeUint8Array (zip.js:283)
    at Worker.onmessage (zip.js:340)
```

**Comment by sgbeal** [comment] 2017-01-24 08:00
fwiw, i archived 8 or 10 books two days ago with no problems. i.e. this is a local problem, not a general one.

**Comment by AndrewD2** [comment] 2017-01-27 02:59
@sgbeal Wondering which program you use and what OS you're reading on, things like that can make a difference.

**Comment by sgbeal** [comment] 2017-01-27 05:15
Chrome 55.0.2883.87 (64-bit) on Mint Linux. The extension says v2.3.3, but since it was installed directly from a fresh checkout, i doubt the version number means much (it hasn't been updated in several months, though, so we likely have the same version).

**Comment by AndrewD2** [comment] 2017-01-27 05:19
Sorry I meant what you use to read the books. Chrome and this plugin are kinda a given, since they're required already.

**Comment by sgbeal** [comment] 2017-01-27 05:25
i read/open the books using several different tools:

- command-line unzip
- "Archive Manager" GUI (for GNOME) v3.16.5
- mcomix (reader for Linux)
- PerfectViewer (reader for Android)

i use the command-line unzip to reorganize/rename the JPG files within the CBZ using a script (i prefer a different naming scheme), then rebuild the CBZ files using zip from the command-line (well, a script). i occasionally use the GUI zip tool just to spot-check the CBZs after download (to see if all pages are there, but i've never yet seen it miss a page), and then i use different readers on Linux and Android.

i.e. there's nothing wrong with the zip files here - they pass through several different tools, each using different zip APIs, just fine.

**Comment by AndrewD2** [comment] 2017-01-27 05:30
OK so do you actually use the cbz's that come from here directly? Because it sounds like you unzip, rename files, and re-zip using something else  than what creates the cbz/zip in the first place. And if that's the case the files working that are wouldn't be valid for my issue. I can open the files with a zip utility just fine and recreate the files with that zip utility fine, but there is something about the way they are created with the extension that they don't directly play in my viewers. I'm going to test some other ones, but the files not working without modification is not just on my system as I've tried them on several others. Currently I download the individual jpgs and have a script that zips them up as cbzs, but the added step should be unnecessary as if I downloaded the CBZs and they worked in the CBZ readers in the first place, I wouldn't have to go that route.

**Comment by sgbeal** [comment] 2017-01-27 05:38
i do both: i spot-check them with the GUI archive tool (and sometimes the mcomix reader), then i unzip and re-zip them using CLI tools. So the generated CBZ goes through at least the GUI zip tool (sometimes through mcomix) before being re-generated locally. Not only that, but my file manager (nautilus) provides thumbnails of the CBZs, and do to that it has to be able to extract the first image. So... at least four tools can read the generated CBZs as-is: "Archive Manager", mcomix, "unzip", and nautilus.

**Comment by AndrewD2** [comment] 2017-01-27 06:20
Well the file works in a different program, but there's still something odd. CBZs from this plugin are the only files I've had not open in CDisplay in the 13 or so years I've been using it. So there has to be something about how they're created that does something weird. It might be something with CDisplay too, but it's just odd and that's why I posted in issue.

I've tried a number of changes to see if it was things like the comments being added to the file or the extra file added to ID people, but removing those items in the code doesn't change it. So there is something here causing a problem. It won't happen for everyone obviously, but it's there. it's at least something I think @Cortys can take a look at. It might be something, it might be nothing, who knows, but it's just an idea. I can continue looking through the code, my javascript is kinda rusty, but I might find something.

**Comment by AndrewD2** [comment] 2017-01-27 07:05
In the end it could just be that CDisplay (not CDisplayEx) has just gotten too old. A number of people have had this same issue with other comics. Most of the other programs I've seen recently (CDispleyEx, ComicRack, and MComix) seem to be using 7zip as their unzip tool, so there's something in the unzip functions in CDislpay that doesn't like whatever is being done to zip the files up here I guess. Might be time for me to change. I'll leave this open and let @Cortys decide if he wants to close it or look into it.

**Comment by sgbeal** [comment] 2018-05-13 09:50
An "access violation", a.k.a. segfault, can only be caused by the viewer software. It's literally impossible for _this_ software to trigger a segfault in other software - all it can do is expose a bug _in that software_ which causes a segfault. This needs to be reported to the CDisplay devs.

**Comment by raycornwall** [comment] 2018-05-13 10:26
You sure it can't be in the zipping scheme used by the extension? With
the fix just being unzip and rezip, something seems off.

----- Original message -----

**Comment by sgbeal** [comment] 2018-05-13 10:30
If the zip files were broken, they wouldn't work in other viewers or in Winzip/7z/etc. i have backed up literally 1500+ books with this extension, and none of the numerous viewers or zip file managers i have used have ever choked on one.

**Comment by raycornwall** [comment] 2018-05-13 10:55
I'm glad it works for you, but clearly I'm having an issue, as are
others. What software are you using (browser, Windows CBR reader, etc)?

----- Original message -----

**Comment by sgbeal** [comment] 2018-05-13 11:49
My point is that the issue that you and others are reporting is not (_literally cannot be_) a problem with this software. i've used MComix (Linux), at least 4 different Android cbz viewers, and no less than 3 different zip managers on these CBZs (all on Linux), and they have all worked flawlessly. A segfault can _only_ come from the software which is segfaulting (this is not speculation but a technical fact - i say that as a life-long software developer). It's literally technically impossible for this plugin to be causing a segfault in other software. The only technical explanation for this problem is that it does "something" which exposes a bug in that crashing software. What that something is, i can't say, but i can say that it doesn't affect all _other_ software, so the origin of the problem is 100% clear: the program which is crashing.

i'm not discounting that you and others are having this problem. i'm trying to help you resolve it by pointing out its source (which is, with 100% certainty, not this software). The solution is to send a failing CBZ to the creators of CDisplay and let them run it through a debugger. With any luck they'll have it patched in a matter of hours. On the other hand, no amount of blaming the problem on this software is going to get it fixed.

**Comment by sgbeal** [comment] 2018-05-13 13:27
Agreed 100% except that i'll replace "both bugs" with "both alleged bugs". So far there's exactly one program affected and over a dozen unaffected, so there's zero evidence that this plugin is any any way responsible. The proposed hypothesis is 100% feasible, but consider: how likely is it that _all other_ CBZ/Zip software is working around (or ignoring) a specific sort of malformed zip which CDisplay trips over? The odds of that seems exceedingly low.

In any case, yes: the first step in any solution is to report it to the CDisplay team and provide them with a CBZ which triggers the problem.

**Comment by raycornwall** [comment] 2018-05-13 18:43
Sigh. The problem is that there is no CDisplay team anymore.

**Comment by raycornwall** [comment] 2018-05-13 18:46
What cbr/cbz programs would be acceptable to test my files on?

**Comment by sgbeal** [comment] 2018-05-13 19:29
The viewer i use on my desktop (which admittedly accounts for <1% of my comics reading) is MComix, which is also available for Windows:

https://sourceforge.net/projects/mcomix/files/MComix-1.2.1/

MComix is trivial to use and works well (at least on Linux), but (like CDisplay), _seems_ to be no longer maintained. There are several clones and forks of mcomix on github, but i've no idea which, if any, of those are actively maintained.

Here's an article which covers 5 readers for the major desktop OSes:
https://www.howtogeek.com/321394/the-best-comic-book-readers-for-windows-mac-and-linux/

On Android (99%+ of my comics reading) i prefer PerfectViewer.

Because CBZ files are just plain old zip files, any program which can read zip files is reasonable place to test them. There's nothing magic about CBZ which makes it comic-specific: the CBZ extension is just the conventional name for ZIP files which contain only images (comic book pages). For full details (plus links to CBZ software), see wikipedia:

https://en.wikipedia.org/wiki/Comic_book_archive

**Comment by Cortys** [comment] 2018-08-29 14:44
I consider this to be a bug in CDisplay. If however someone finds a way to make the output of zip.js (the zip library this extension uses) compatible with CDisplay, I'm of course open to merge a PR. Closing this for now.

**Closed by Cortys** 2018-08-29 14:44 UTC
Labels: won't fix
